consume_filament:
  target:
    entity:
      domain: number
      integration: filament_manager
  fields:
    amount:
      required: true
      example: 25
      selector:
        number:
          min: 0.1
          max: 100000
          unit_of_measurement: g
          mode: box

refill_spool:
  target:
    entity:
      domain: number
      integration: filament_manager
  fields:
    amount:
      required: false
      example: 1000
      selector:
        number:
          min: 0
          max: 100000
          unit_of_measurement: g
          mode: box
